CREATE DATABASE TemplateManagerDB;
GO

USE TemplateManagerDB;
GO

CREATE TABLE Users (
    Id VARCHAR(150) PRIMARY KEY,
    Email NVARCHAR(200) NULL UNIQUE,
    PasswordHash NVARCHAR(MAX) NOT NULL
);

CREATE TABLE Templates (
    Id VARCHAR(150) PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    Html NVARCHAR(MAX) NOT NULL,
    UserId VARCHAR(150) NOT NULL,
    CONSTRAINT FK_Templates_Users 
	FOREIGN KEY (UserId) REFERENCES Users(Id)
	ON DELETE CASCADE
);